// Three visual directions for the Subhan Complaints form.
// Each theme defines its own palette, radius rhythm, and type pairing.

const THEMES = {
  service: {
    name: 'Service',
    blurb: 'Warm whites · deep emerald',
    bg:           '#F4EFE5',
    bgGrain:      'radial-gradient(circle at 50% -10%, #EFE6D3 0%, #F4EFE5 55%)',
    surface:      '#FFFFFF',
    surfaceMuted: '#F0EAD9',
    chip:         '#EDE6D2',
    fg:           '#161F1B',
    fgMuted:      '#6B776E',
    fgFaint:      '#9AA59C',
    border:       '#E1D9C5',
    borderStrong: '#C9C0A8',
    primary:      '#0F5D4E',
    primaryHover: '#0A4B3F',
    primaryFg:    '#F7F3E9',
    accent:       '#B47339',
    accentSoft:   '#F2E4CF',
    danger:       '#B43D2E',
    success:      '#0F5D4E',
    radius:       18,
    radiusSm:     12,
    radiusLg:     26,
    headerFont:   "'Geist', system-ui, sans-serif",
    bodyFont:     "'Geist', system-ui, sans-serif",
    monoFont:     "'Geist Mono', ui-monospace, monospace",
    titleWeight:  600,
    headerCase:   'normal',
    headerLetter: '-0.02em',
    label:        'Hum sun rahay hain',
    tagline:      'Tell us what happened — we read every message.',
    pillStyle:    'rounded', // rounded | square | capsule
  },
  editorial: {
    name: 'Editorial',
    blurb: 'Crisp navy · serif headers',
    bg:           '#FBFBFB',
    bgGrain:      'linear-gradient(180deg, #FFFFFF 0%, #F4F4F6 100%)',
    surface:      '#FFFFFF',
    surfaceMuted: '#F2F3F6',
    chip:         '#EEF0F4',
    fg:           '#0A1230',
    fgMuted:      '#5C657F',
    fgFaint:      '#9098AE',
    border:       '#E3E5EC',
    borderStrong: '#C7CBD6',
    primary:      '#0A1A4A',
    primaryHover: '#070F33',
    primaryFg:    '#FFFFFF',
    accent:       '#3956D9',
    accentSoft:   '#E6EBFB',
    danger:       '#C32F2F',
    success:      '#1E6B4A',
    radius:       8,
    radiusSm:     6,
    radiusLg:     12,
    headerFont:   "'Source Serif 4', 'Iowan Old Style', Georgia, serif",
    bodyFont:     "'Manrope', system-ui, sans-serif",
    monoFont:     "'Geist Mono', ui-monospace, monospace",
    titleWeight:  500,
    headerCase:   'normal',
    headerLetter: '-0.03em',
    label:        'Complaint intake',
    tagline:      'Recorded directly to management. Every entry receives a reference.',
    pillStyle:    'square',
  },
  clay: {
    name: 'Warm Clay',
    blurb: 'Terracotta · cream',
    bg:           '#FAF1E0',
    bgGrain:      'radial-gradient(circle at 20% 0%, #F7E3C0 0%, #FAF1E0 50%)',
    surface:      '#FFFCF4',
    surfaceMuted: '#F3E6CC',
    chip:         '#F0E1C2',
    fg:           '#33180D',
    fgMuted:      '#7A5A48',
    fgFaint:      '#A99277',
    border:       '#E8D6B6',
    borderStrong: '#D4BC92',
    primary:      '#BB4F2E',
    primaryHover: '#9E3F22',
    primaryFg:    '#FFF8EC',
    accent:       '#6F7B3B',
    accentSoft:   '#EDE6CB',
    danger:       '#8B2E1F',
    success:      '#6F7B3B',
    radius:       22,
    radiusSm:     14,
    radiusLg:     30,
    headerFont:   "'Manrope', system-ui, sans-serif",
    bodyFont:     "'Manrope', system-ui, sans-serif",
    monoFont:     "'Geist Mono', ui-monospace, monospace",
    titleWeight:  700,
    headerCase:   'normal',
    headerLetter: '-0.025em',
    label:        'Aap ki baat zaroori hai',
    tagline:      "Your voice matters. We'll follow up within 24 hours.",
    pillStyle:    'capsule',
  },
};

window.THEMES = THEMES;
